---
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: bug-backup-gcs-br-119-409-prefix
  namespace: default
spec:
  br:
    cluster: basic
    sendCredToTikv: true
  gcs:
    projectId: pingcap-real-testing-account
    bucket: lyl-backup-bug-test-br-119-409-prefix
    prefix: br-119-409-prefix
    secretName: gcs-secret
